(function($) {

	function displayImages( p1_a_infos_img) {
		return `<img src="${p1_a_infos_img.src}" style="border: 1px solid #ccc; border-radius: 5px; padding: 4px; height: ${p1_a_infos_img.height || 'auto'}; width: ${p1_a_infos_img.width || 'auto' }"/>`;
	}

var B = 'Bogota';
const ipfsHashs = ["QmeTpNYFSHvWVGU7sbrVGuqyhFTAK89g1BCtTqqZ4jCrFY","QmUgUtwcKEG3gf7GsAukF8ozThbEeND3Hp3C5MbDpwCGae","QmbYveXPifjs4PUytYrCGdcwhukXzuyZnKtAmwT3xWKejP","QmeMEUBJri52evzcw6Ru9Fw3eeXVgkSG2VAg8XMyUo6Wue","Qmah2PVcsrHRFJuehchPTbofbGaLgmtg9LifqQgSEeJDV2","QmdfMx2561kDPKNWcFKeCkBbxwxDoBsZwU72QspE3u7YYg","QmULP3PBSkWKoYmcYC1Ej3PzGPjTqiVJ1G6R1i4FGppttj","QmbhZEx11kFfJLT5dNfieywxdzDbWZudbcJehxNcPqFvXq","QmQZHcLFbgYWFMfMsg6SbtJzK28ssjUG9ZWiGTuFKgcTJF","QmSKec5CCffkfM5YXBNpyrZfc944hojmKNx5R9hUC82dFq","QmZDb4Lwj7jKxxf7wjaNcv1Tcc6UG24sXeF4sUDAhx1PL7","QmakrqFujPFzpfCyaVcsCh7uySBZ6P1rDynCNuYWqDbho9","QmQkqvMsTurxYez4cV1dvCKY45nimbUQaXHutrVR2eHcPU","QmNXcGWcURmoWN9roXxjJ5tCF6FErzEF6E1i2C77eYSCWt","QmUMWHr5XtqQeGsRgjTnXfdLKjpHtRfVqVoEkPKbSADYqq","QmZSNMfXS1qby2J1XaP1TA8AdH1GxNWNGcL8rK2R9VwaeR","QmXszZoYkNpAaCKeXjupw89CfPPMg55DW1MgX43n9cfGRr","QmWJAqcLvu9otMaiZT21M1DThFQvzNrDmWiabhePzbgufB","QmYPusgJP3KYYivH9sapMe2BQDpfVwFMFNSLeqRnsCAPdo","QmeYPRi9bGUrtb7Pz6DNHDeLCiWjn3LgbFaUs6NTRZWx5m","QmZkWnb3hXT9u2xaLvChtmwp5gLNV2PRjbqWq5BCzf7bU4","Qmen6i3ktysMUDW6ukRPM6Znx6GjptSxT8Tyu5Bd2J75EB","QmfV9FRgBqQaGG9nYHZE8mdW65p5rfiVaeUbF98sDtBoUN","QmaMt4wgaN55qfLbjujF5AKUTshfPR2guzt4UgkdBKXUk6","QmZzJGi78iiqE4FCJErP4HyqaNhttxHU3Q4cLwrXSvUZYa","Qmd51CA5Ga5B8HmTrCYVdeb2pksCCxbRFsw5Q4hYw4iHWD","QmQni7xUoL2dSPmNLg1iNRooKu7h4YHziX7yw673KnRAaR","QmdbkMJ1gFUk7gNPZP6ALrVE8ZseGc58NPfvX5uD76CH7i","Qmaray4cjH2cYBYkjcWgTCYBxY84oaQixhDk1Vq7NYj7NJ","QmcCNfmmDU6rPDPUXeWTn9VDRGhCky98jSt4bSdixX5TuA","Qmf3V76Yq2kxq8vuB5Re194EBY2nQLCawGbFitbQ3XT98D","QmZoWSVZvTMgoGeQnXiRoY4oYuySU1GHySwEDCxknLuea1","QmPT9HTVzrYAWhQ23r24G2oRrdWDBohkYibbiTYVn8LeDU","Qma7WHQ6ixgUuCtt4MDbwPfkgHWSVzJhDXLyXtLyfduycX","QmQ9jFu7axKzPqQQEZJtwcyFGYYaLknSmVhrcDjeuABLXe","QmWmSJivCi6XZfAQHPAjovmHxwm2vSyBCkzUXbyiKR8jK7","QmdZXpzk5P5Lp8W4zddW5P27WvBaFUrTbGFFJ3T92EA9vk","Qmde8icyLnkTGsP4H4pGcXapgjye8JLSVtyKz8BmptibDW","QmSV6JDoiezX7CNATPKgMWHPtTRQKLdDLLF4nCqYPhupNz","QmVfRQQ7Md6uC3YLdPcgyHU9EfYcb3Uc2eGZpmvH8rhRZM","QmNSspMb1igT7bcjhpE1DtwhoKysnHsRZ9RzLtmDnLtp3b","QmcgNszveKwBNWUUGSgid16wE5hApFF39knEe1NhkrHDSt","QmVuQ6qFwWmFmqiHKuyTHQGivtMfCukxXFLjdAzR2ce98b","QmR2gTXfXTzVDkY26A3z57Av9sipkCNYc5TXJpdCbfNjL9","QmZbTQKnY5UjdS3nLMVDEpRE4WxNTHR8UDP4xszhKc9L2M","QmZhZopoXsRGS8Yt9EznV9BQ4y6Tum1gDLFkYVHFFSVoKE","QmWmz6LVVDvrjcx29hkbGsbMbYavRxxabmxTwXkNFHjTrF","QmNNwEknB7BPdgz7bsH2bKYKDqgvWWfohNKfiinuw7Fxjj","QmSw4WNmV4RvB6Q1LkWMFXdnDUBUp4gkHntzFSmcxMj4ma","Qmb2r2wjrdQuAgE5VAnRwkKNdTdMiMjX2cnGQHyoFwZm2f","QmUGJQykiFPtEX8C99JRHL267FkpM5hK9KD2UAYzqCyAKK","QmQZ1rfpJrdVbRdSF2pTMx9aMmCTaNFcXjgfHGA5LT4qpo","QmSNnMGs9yND3QT3MuhJZaMJHxeeDCJ8tW64EMTTGocCCo","QmcLicHbxate3G5L1aCv9tduDivWo1g5rPKuLnNNwrizWM","Qmb9y11btTRaHqMH37aExeimFYy1RAhypoVn3oVoFV4Xqv","QmWVP7uxf3Ph4pi5ZU8Ss78ZCMeNseNMwxGND5b6swWnab"]
var s3_url = 'https://arturo.infura-ipfs.io/ipfs/';

var s_hammock_song_gdrive = 'https://arturo.infura-ipfs.io/ipfs/QmeBYoWFw5LVbVS7VesDmqmbWdV1wUGcer3ZNELB3HZ8LM';

var s_day_1 = "<p class='t'>09/02/14</p><p>Après avoir passé mes deux vols aux places situées aux sorties de secours en compagnie d'une maman hispanocolombienne lors du second vol, j'arrive comme une « abstraction » dans un pays où je suis autant colombien qu'un local administrativement parlant mais non pas culturellement et linguistiquement.</p><p>Ma première impression concerne la météo : je m'attendais à ce qu'il fasse plus frais mais il fait relativement bon pour au moins 3 raisons probablement: humidité, pollution et chaleur générée et préservée par le bitume après que le soleil d'équateur eut tapé dessus tout au long de la journée. Le rythme solaire est simple : 06:30 am -> 6:30 pm. La langue parlée semble être très proche de l'espagnol de madrid mise à part des mots différents et les doubles L se prononcent « dj ».</p><p>La pauvreté est encore bien présente : on peut passer d'une rue très fréquentée avec des boutiques modernes à une ruelle très sale où des mendiants fouillent dans les poubelles. L'altitude rend plus difficile les efforts physiques (monter une pente). Logement dans un hôtel au concept auberge espagnole (avec des jeunes venus d'europe et amérique latine) dans la Candelaria qui est un quartier typique populaire du centre sud-est de "+B+"</p>";

var s_day_2 = "<p class='t'>10/02/14</p><p>J'ai quitté l'hôtel pour faire du change le matin mais j'ai oublié mes euros. Ensuite vers la calle 4 pour acheter un forfait virgin mobile mais je me suis rendu compte que par là-bas il ne pouvait rien y avoir qui ressemble à un magasin. Conclusion : encore fatigué car pas malin et attentif et aussi, toujours lancer un street view si l'on n'est pas certain de sa destination.</p><p>Retour aux alentours de la place Bolivar pour faire des courses dans un super marché. Je n'ai toujours pas sorti mon reflex pour prendre des photos. J'ai fait une petite heure de télétravail après déjeuner. En début d'après midi j'ai commandé un taxi pour aller acheter un forfait virgin mobile dans centre commercial Exito au barrio chapinero. Pour 50 dollars US on a 4h d'appel et 2go d'internet en H sur une carte sim rechargeable. Le fait d'avoir la cedula de cuidadania m'a semble-t'il bien facilité la tâche.</p><p>Retour à l'hôtel en Transmilenio dans les rush hours (c'est presque pire que le tramway d'Istambul). Heureusement je suis tombé sur un bus vide au départ de ma station. Pour clôturer cette journée, j'ai participé à une cuisine en commun dans la cuisine de l'hôtel tout en faisant connaissance avec les autres jeunes: des Russes, Indiens, Anglais, Mexicains, Danois.</p>";

var s_day_3 = "<p class='t'>11/02/14</p><p>Départ pour l'orphelinat la Casa de la madre y del nino en taxi. C'est un endroit propre, accueillant, chaleureux, bien situé et entretenu. Première impression: sérieux. Je me présente en quelques mots et explique que j'aimerais bien visiter l'endroit et prendre quelques photos. Sarah, une ancienne orpheline de la Casa vivant en italie me fera visiter l'endroit et me présentera un peu le personnel et les enfants. L'ensemble du personnel est très accueillant et disponible. On me propose de revenir après déjeuner pour pouvoir discuter avec Barbara (directrice) et son bras droit.</p>";

var s_day_3_bis =  "<p>J'ai eu dans la foulée un rendez-vous à 30 secondes à peine à pied de l'orphelinat pour visiter une chambre dans appartement où vit une jeune étudiante et sa mère. L'appartement est calme, bien situé et « gardé » 24 heures sur 24 à l'entrée! Repas avec la famille qui heureusement ne parle pas un mot d'anglais même si la fille comprend l'anglais basique. On a eu la visite d'un des frères pendant le repas. Bref les membres de la famille semblent très corrects.</p><p>Après avoir posé l'essentiel des questions sur l'appartement, discuter du prix du loyer et des activités à faire aux alentours je retourne à la Casa. Rencontre avec le bras droit qui me laisse regarder les archives concernant le dossier de la famille grégoire huc. Elle me propose d'y lire une sorte de petite biographie sur la situation de ma mère biologique à l'époque de son accouchement mais je lui dis que seuls les éventuels problèmes de santé qu'elle aurait pu avoir pourraient m'intéresser, mais ils ne conservent malheureusement pas ce genre d'informations. Je leur donne des photos d'identité de moi à 4-5 ans, 16-17 puis 27 ans pour qu'ils aient l'évolution de mon portrait et laisse un mot sur leur livre d'or. Nous discutons ensuite avec Barbara qui me pose des questions sur ma vie depuis et celle de ma famille. Elle me proposera de faire un peu de bénévolat si j'en ai envie.</p><p>Retour à l'hôtel Masaya en Transmilieno encore mais en dehors des heures de pointe et c'est bien praticable. Je suis sorti de nouveau en direction d'une banque afin d'avoir des infos concernant l'ouverture d'un compte mais elles ferment à 16:00. Enfin nous allons nous promener dans la Candelaria jusqu'en début de soirée avec une Russe originaire du Caucase (habitant près de Sotchi) avec qui j'avais déjà un peu sympathisé la veille. On repère quelques endroits à visiter pour plus tard.</p>";

var s_day_4 = "<p class='t'>12/02/14</p><p>Passage au bureau bancolombia le plus proche de l'hôtel afin d'avoir le maximum de renseignements sur l'ouverture d'un compte locale et de déterminer si cela peut être moins « argentivore » que de payer à chaque fois des frais de retrait à l'étranger plus des taux de changes. Finalement c'est assez cher et surtout lorsqu'on veut virer depuis un compte étranger où il y a au minimum 30 dollars de commission. Vianey, le manager de l'hôtel, m'expliquera qu'HSBC cessera de fonctionner en colombie 3 semaines plus tard et que même si c'est la meilleure banque colombienne en terme d'opérations internationales, il vaut mieux pour les gens qui restent moins d'un semestre, retirer 2 ou 3 fois par mois des grosses sommes d'argent à conserver chez soi et sortir au fur et à mesure. Les colombiens payent plus souvent en espèces qu'en cb.</p>";

var s_day_4_bis = "<p style='margin-top: 5px; margin-bottom: 0px;'>Retour à l'hôtel où je propose à un mexicain d'aller visiter le musée Botero avec la même jeune Russe de la veille. Avant d'aller au musée nous décidons d'aller prendre quelques photos sur la place Bolivar. Même en plein milieu de journée il est difficile de prendre des photos sauf aux endroits touristiques. De manière générale il est déconseillé d'exhiber ses affaires de valeurs. Le musée Botero est à 5 minutes de l'hôtel Masaya. Il est sur 2 étages et bien fourni et aussi des œuvres d'autres artistes. Nous sommes ensuite allés déjeuner dans un bon restaurant mexicain mais un peu cher.</p>";

var s_day_4_bis_p2 =  "<p style='margin-top: 0px;'>L'après midi je suis allé découvrir le mont serrate à plus de 3000 mètres d'altitude permettant d'avoir une vue sur le sud de la ville. La montée à pied ferme à 15 heures et seul le téléphérique était disponible car le funiculaire en réparation. Je suis ensuite rentré à l'hôtel pour me reposer et discuter avec un danois qui parcourt en solo et en moto le nord de l’Amérique latine. Victoria, une des hôtesses et animatrices de l’hôtel, m'a conseillé de dîner au restaurant à côté où j'ai commandé un filet de pescado avec frites et une bière noire colombienne. Puis à 20h elle à donné un cours de rumba aux jeunes dans la salle du petit déjeuner.";

var s_day_5 = "<p class='t'>13/02/14</p><p>Rien de bien particulier pour cette journée. J'ai commencé par un petit déjeuner à 7 heure comme tous les matins depuis mon arrivée et j'ai échangé quelques mots avec la serveuse du matin, Carmen, très gentille avec un visage et un sourire très accueillants. Chaque matin il y a un jus de fruit différent et des fruits tropicaux différents. J'ai préparé ma valise et télé-travaillé une heure pour achever une mission avec des français qui dirigent une association sportive.</p>";

var s_day_5_bis =  "<p>Ensuite, taxi en direction de la famille Gutierrez pour m'installer et déjeuner. Je comptais aller visiter l'université pédagogique de "+B+" pour les cours d'espagnol pour étrangers mais la première grosse pluie depuis que je suis arrivé m'en a empêché. A la place, Jacquelin une amie de la famille a proposé de me faire une pédicure et puis j'ai discuté informatique et internet avec Ruben, le copain de la fille.</p>";

var s_day_5_bis_p2 = "<p>Du début d'après-midi jusqu'à 21h, nous avons parcouru à 3 le nord de "+B+" puis avons dîné dans un restaurant Wox servant des plats asiatiques. Nous sommes rentrés en taxi car trop fatigués par la marche. "+B+" est une grande ville comparable à NYC par sa superficie et le fait qu'elles s'étendent du nord au sud et non pas comme Istanbul par exemple, d'est en ouest.</p>";

var s_day_6 = "<p class='t'>14/02/14</p><p>J'ai commencé cette journée par pirater un réseau wifi wep d'un voisin pour avoir une meilleure bande passante si celle de la famille venait à être saturée. Après le petit déjeuner, Jacqueline, qui m'a fait la pédicure la veille est venue me chercher en scooter pour m'emmener à l'université pédagogique de "+B+". En dehors des grands axes les routes ont souvent de gros trous. De toutes les façons on n'avance pas vite aux heures de pointes et "+B+" est très polluée. Je discute en espagnol et anglais avec la personne chargée du cursus « espanol por los extranjeros » et elle me dit que la prochaine session sera seulement milieu, fin avril. Ce qui est trop juste pour moi car je dois rentrer début juin. Elle me parle d'université privée mais le prix sera évidemment plus cher donc je n'irai pas voir. Avant de partir je lui pose tout de même la question de savoir s'il est envisageable de donner des cours de français étant donné que j'ai une licence dans mon pays et que j'ai aussi la nationalité colombienne. Elle m'a répondu qu'ici en tout cas, cela ne sera pas possible en raison des futures élections présidentielles.</p><p>Une fois au courant, Jacqueline me proposera d'aller visiter un institut privée de langues étrangères à 10 minutes à pied de ma chambre. Elle connaît un peu cet institut car une amie y travaille. J'ai présenté mon parcours et dressé mon profil à une professeur d'anglais. Celle-ci me proposera dans un premier temps de me donner des cours particuliers et par la suite très probablement que je donne des cours de français à des groupes de 5, 6 personnes. On se donne donc rendez-vous le lendemain à 9 heures pour un premier cours, évaluer mon niveau d'espagnol. J'invite Jacqueline à déjeuner et lui dis que cela serait pratique que j'achète un vélo. Elle propose qu'on aille dans un centre commercial mais les vélos que j'ai vu là-bas m'ont fait peur et j'ai préféré qu'on aille dans une boutique spécialisée. Cette fois-ci les vélos étaient plus solides et toujours bon marché.</p>";

var s_day_6_bis = "<p style='margin-top: 0px;'>J'ai dit que je préférais payer plus cher un vélo avec lequel je n'aurai pas des problèmes tous les jours plutôt que l'inverse. Avec 215 dollars j'ai acheté un vélo avec des freins à disques, un cadenas et un casque. Jacqueline a proposé de mettre le vélo dans un taxi mais je lui ai dit que je pouvais rentrer en vélo. Une fois rentré à l'appartement j'ai fait une  heure de télétravail mais il y a eu ensuite une heure de coupure d'électricité qui paralysa une bonne partie du quartier car les réseaux wifi des voisins n'étaient pas disponibles. Le soir je suis sorti au centre commercial le plus proche pour dîner et faire les courses du petit déjeuner. La rue qui y mène depuis un certain point après l'appartement pourrait être celle d'une rue de los angeles: des boites de nuit, des grands restaurants et cafés, modernes aussi. Arrivé au supermarché j'ai commandé un menu dans un fast food « el corral » qui, comme Ruben me l'avait dit, n'ont rien à envier aux mac donald's. Jetez un coup d'oeil au site : <a href='http://www.elcorral.com' target='_blank'>El Corral</a> . Les frites ont du goût, un vrai goût et les hamburgers sont meilleurs et bien plus grands. Dans ce quartier c'est finalement pas très dangereux de se balader la nuit.</p>";

var s_day_7 = "<p class='t'>15/02/14</p><p>Départ à 8:45 am pour mon premier cours d'espagnol dans un institut privé avec Edna, la professeur d'anglais. Révision des bases pendant 3 heures et comme je disais à Julien, si l'espagnol revient vite il repart aussi assez vite car on le pratique moins que la langue de Shakespeare. Edna nous a invités à déjeuner avec l'autre élève qui apprenait l'anglais. Je lui ai ensuite expliqué que 2 heures 3 fois par semaine devraient me suffire pour commencer car je dois aussi gagner un peu de sous et consacrer du temps pour trouver un travail sur place.</p><p>Je commence un nouveau projet pour une association sportive française mais rapidement je suis irrité car je ne peux presque pas m'asseoir à mon bureau pour travailler tant les meubles sont mal disposés dans la chambre. De toutes les façons j'ai lancé un upload FTP parti pour durer une heure et j'ai donc le temps de rendre mon espace de vie plus ergonomique. Lorsque Magnolia (la mère de la famille d'accueil) me voit reconfigurer la pièce, elle semble contente de mon initiative et propose de m'aider car je dois quand même soulever le lit double qui prend bêtement trop de place dans la longueur alors qu'il doit pouvoir rentrer dans la largeur. C'est bon ! Résultat de l'intervention. Je peux déjà m'asseoir pour travailler avec plus d'1 mètre derrière moi et avoir la fenêtre (et la lumière) en face de moi plutôt que le mur. Je peux ouvrir mes placards sur la gauche sans que la télé (dont je ne me sers pas) gène. Je peux manipuler et fenêtre et rideaux sans avoir à marcher sur le lit. Je peux éteindre ou allumer la lumière depuis mon lit.</p>";

var s_day_7_p2 = "<p>En milieu d'après midi nous allons faire des courses supplémentaires avec Magnolia dans une sorte d'Aldi du coin où j'ai pu faire mes courses du petit-déjeuner pour 8 dollars pour une semaine avec des produits de marques (Nestlé, Kellogs). J'achète de quoi faire mon premier dîner, pas fameux. Je pirate un second réseau wifi car c'est la meilleure heure. Je continue de travailler un petit peu et consacre un peu de temps à la mise à jour de la version espagnole de mon CV.</p>";

var s_week_2_p1 = "<p class='t'>Semaine 2</p><p>Ma seconde semaine fût bien moins chargée que la première. J'en ai surtout profité pour installer des accessoires supplémentaires dans ma chambre : petites enceintes, écran plat ordinateur, changement d'ampoule et achat d'une « boule » pour la couvrir. J'ai passé mes deux premières matinées à intégrer mon récit de voyage et les photos  dans ce flip book (<a href='http://www.turnjs.com' target='_blank'>turn.js</a>).J'ai effectué ma première matinée officielle de bénévolat à l'orphelinat. La première impression est que les enfants débordent d'énergie et c'est parfois difficile de les contenir, mais ils doivent être un peu plus excités quand il y a une nouvelle personne pour passer du temps avec eux. Il y a 2, 3 enfants qui sont autour de la dizaine ou l'ont déjà dépassée. C'est même très bruyant dans la ludothèque au moment de leurs temps libre. Quoi qu'il en soit, c'est une bonne chose de pouvoir être au contact des enfants pour pratiquer mon espagnol basique.</p><p>L'appétit est féroce quand le déjeuner commence à 14h et qu'on est là depuis 9 heures du matin. Ce premier déjeuner gracieusement offert par l'orphelinat était bon et copieux. J'étais assis entre Barbara la directrice et sa fille. J'étais la seule présence masculine autour de la table. En ce qui concerne la météo c'est chaque jour le même scénario : beau temps et frais le matin puis cela se couvre et se réchauffe au fur et à mesure pour dégénérer en pluie diluvienne en début d'après midi avec parfois des orages. Puis il fait 5 degrés de moins.</p><p>Mardi matin j'ai aussi avancé sur ce flipbook et j'ai fait 5 heures de télétravail l'après-midi.</p>";

var s_week_2_p2 = "<p>De 8 à 10h, le lendemain mercredi j'ai eu mon premier cours où Edna m'a fait faire un test d'évaluation (QCM) où j'étais un peu au-dessus de la moyenne. La seconde partie du cours s'est faite dans la rue en retenant les mots de choses qu'elles me montrait. Je me suis dépêché de pédaler vers l'appartement pour ensuite finir la matinée à l'orphelinat.</p><p>Je pense avoir fait des courses le jeudi matin puis déjeuner 4 dollars us (seulement plat principal) dans un petit restaurant au sud sur la calle 45. L'après-midi j'ai décidé d'aller prendre des informations sur le cursus « espagnol pour les étrangers ». La prochaine session démarre fin mars début avril (je devrai rappeler plus tard pour avoir les dates exactes). Les examens d'évaluation de niveau ne sont pas obligatoires mais par contre il n'accepte plus d'étudiant au delà de 2 jours de retard, j'avais 5 jours malheureusement quand je suis arrivé. Je compte bien m'inscrire donc. Environ 350 dollars us pendant 2 mois à raison de 2 heures par jour et chaque jour de la semaine. Encore une fois j'ai de la chance car je suis à 10 minutes à pieds de l'entrée de l'université nationale et il me faut encore 5 bonnes minutes pour aller jusqu'à l'autre bout car c'est là-bas que se situe les locaux dédiés au cursus des langues.</p>";

var s_week_2_p3 = "<p>Vendredi, Edna n'a pas pu assurer son cours mais elle m'a proposé que son mari, Michael m'accompagne au barrio chapinero pour acheter un écran plat d'ordinateur. Voilà pourquoi je n'ai pas eu le temps de déjeuner à la casa mais de toutes les façons j'étais arrivé une heure plus tôt. J'ai pas mal discuté avec Michael, hollandais, avec beaucoup d'expérience de voyages car il a vécu dans plusieurs pays différents. J'ai décidé de repartir avec un écran 17 pouces de seconde main garantie 6 mois pour environ 75 dollars us. C'est plus pratique pour travailler.</p><p>J'avais une soirée de prévue pour rejoindre la femme (qui est colombienne) d'un ancien camarade d'université, (Théo Zachmann que j'ai rencontré par hasard quand je suis allé faires mes dernières démarches administratives au consulat colombien à Paris), mais cela n'a pas pu aboutir, toujours pour la même raison : on a une adresse mais c'est en fait assez difficile de savoir exactement où l'on va car chercher dans google maps marche une fois sur trois. J'ai pourtant bien demandé à Ruben de m'aider à chercher et il m'a dit que c'était à cet endroit précis et que je pouvais y aller en vélo. Ensuite, le gardien m'a conseillé d'y aller à pieds car la nuit en vélo c'est prendre beaucoup de risques et aussi de ne pas prendre trop d'argent... Résultat quand je suis arrivé après 20 minutes, j'ai demandé de l'aide à des passants qui m'ont dit grosso modo que j'avais parcouru qu'un tiers du chemin et que le restant à faire devenait vraiement dangereux. Comme je n'avais ni de vélo, ni d'argent pour un taxi la soirée s'arrêtait là pour moi.</p>";

var s_week_2_p4 = "<p>Le lendemain matin j'ai décidé de refaire totalement la landing page de mon site. En début d'après midi, la belle fille de Magnolia est venue nous rendre visite avec son fils. Le grand frère de Magnolia est aussi passé pour avancer sur ses démarches de retraite (à 60 ans) avec une spécialiste. On a un peu discuté. En fin d'après-midi j'avais un rendez-vous avec une colombienne qui avait choisi le centre commercial gran estacion comme point de rencontre mais elle n'est jamais venue et pas moyen de la joindre... J'en ai profité pour faire des courses.</p><p>En rentrant à l'appartement, un nouvel arrivant s'était installé dans ce que j'appelle « el habitacion de los perros » car ils vont souvent s'allonger sur ce lit. C'est un futur étudiant colombien de 23 en physiothérapie. Les sports sont donc sa passion et on espère s'inscrire dans un gymnase pour faire un peu de musculation ensemble. Enfin, le dernier jour de la semaine nous sommes allés sortir les chiens, qui à mon goût restent trop longtemps dans l'appartement avec la terrasse comme seul endroit au dehors. La preuve, ils étaient très excités en sortant. Courses puis repos l'après-midi. J'en ai profité pour m'inscrire sur <a href='http://www.netflix.com' target='_blank'>Netflix</a> qui est disponible en Colombie avec comme choix de langues : anglais, espagnol, portugais du Brésil mais le catalogue est faiblard.</p><p>Ce que j'ai constaté et appris de cette semaine : les femmes sont plus typées que les hommes et d'ailleurs comme me l'a expliqué Michael, il y a eu a un moment donné dans l'histoire de la colonisation de l'amérique latine (surtout au Pérou) par les grands navigateurs une forte immgration de population philippine (d'où le fait probablement que certaines femmes surtout ont les yeux presque aussi bridés que des asiatiques). D'ailleurs en anglais, un des rares mots qui soient totalement espagnol, comme 'mosquito' est celui qui désigne les Philippines: Filipino.</p>";

var s_week_3_p1 = "<p class='t'>Semaine 3</p><p>Encore moins d'événements particuliers pour cette semaine. Je commence même à rentrer dans une petite routine rendant ce récit plus laconique. On est donc allés s'inscrire pour un un mois dans une salle de musculation (la plus proche à 5 minutes à pieds c'est pas ce qui manque ici) avec Leonardo. Ils appellent cela des « gymnasios », alors je me demande comment ils appellent les salles de sports acrobatiques ? On a fait une première session dans la foulée. Je suis content de pouvoir profiter d'un futur étudiant en physiothérapie qui pourrait très bien déjà travailler en tant qu'instructeur dans une salle de muscu car il connait toutes les machines. Je trouve la muscu ennuyeuse car c'est plus un moyen pour pouvoir faire d'autres sports et pas une fin en soi mais il faut que je transforme mon ventre en abdos... On y est donc allés chaque jour de la semaine sauf jeudi.</p>";

var s_week_3_p2 = "<p>Mon programme a quasiment toujours été le même : je vais aux cours d'espagnol à vélo puis repasse à l'appartement pour déposer mon vélo avant d'aller « travailler » à l'orphelinat. C'était l'anniversaire de Barbara vendredi mais elle n'était pas là, dommage ! Une question que je m'étais déjà posée depuis un moment mais avais oublié de chercher au moins un début de réponse sur internet : que dois faire un homme ayant une double nationalité dont les pays de ses nationalités respectives entrent en guerre ? J'ai posé cette question à Edna (professeur d'espagnol, anglais) et on a discuté et fini par conclure, sans vraiment savoir, que le plus logique serait que la personne combatte pour le pays dans lequel elle a le plus longtemps vécu. Sinon Edna m'a affirmé que la Colombie n'exhorte pas les ressortissants \”colombo-quelquechose\" à défendre la Colombie en temps de guerre... Oui, il ne faut pas oublier que c'est la guerre civile en ce moment au Venezuela, un peu comme en Ukraine.</p>";

var s_week_3_p3 = "<p>Cette semaine j'ai aussi discuté avec Oxana pour lui proposer d'aller passer quelques jours sur la côte des Caraïbes la semaine suivante mais dans un premier temps elle m'a dit qu'elle ne pouvait pas quitter son nouveau travail et dans un deuxième temps qu'elle voudrait plutôt aller au Peru visiter le Machu Picchu.  Finalement elle préfère ne pas s'absenter de son travail. Samedi j'ai donc décidé de réserver un aller simple pour le lendemain vers Santa Marta et de revenir 9 jours plus tard depuis Carthagène des Indes. J'ai d'abord regardé sur internet et le plus bas en réservant la veille pour le lendemain est 90€ aller et même chose au retour. Par chance encore, ma famille d'accueil vit dans le même immeuble qu'un de leurs amis travaillant dans une agence de voyage et aussi à l'ambassade française de "+B+"! Il m'a trouvé des billets aller-retour pour 130€ (50€ moins cher). Je pense aller au moins une ou deux nuits dans l'hôtel masaya de santa marta car j'ai une remise de 10% et surtout parce que j'avais bien apprécié celui de "+B+". Ici il fait un temps britannique depuis une dizaine de jours et c'est blasant. Edna m'a expliqué que ce sont des vents qui viennent du brésil et nous apporte quotidiennement nuages et pluies en seconde partie de journée.</p>";

var s_week_4_p1 = "<p class='t'>Une dizaine de jours sur la côte.</p><p>Pour casser la routine j'ai donc décidé de réserver un billet d'avion la veille pour le lendemain en aller à Santa Marta et retour de Carthagène. Famille et amis ont été très serviables et généreux. Le voisin d'immeuble m'a  trouvé un billet à meilleur tarif qu'internet (110€ seulement finalement) et le frère de magnolia, chauffeur de taxi pour sa retraite m'a emmené à l'aéroport  le jour de « la ciclovia » (dimanche). Je pense écrire moins de texte pour cette dizaine de jours et donner plus d'importance aux photos qui se débrouilleront mieux que moi pour faire le récit. En moins d'une heure et demie on se retrouve sur les caraïbes et on comprend pourquoi les colombiens disent que les saisons sont géographiques. Arrivé à Santa marta en fin d'après-midi, certes il fait environ 30 degrés mais il y a tout de même un bon vent qui permet de bien respirer. (L'aéroport n'est pas à Santa Marta en fait, 20 minutes de taxi au sud). Première nuit à l'hôtel Masaya avec 10% de réduction. Il est vraiment différent de celui de "+B+" : plus grand, luxueux mais (pas forcément paradoxalement) avec une ambiance moins chaleureuse qui caractérisait si bien celui de "+B+", c'est à dire avec les jeunes étudiants venus des quatre coins du monde.</p>";

var s_week_4_p2 = "<p>L'hôtel étant vraiment trop cher, on s'était donné rendez-vous avec une étudiante de Santa Marta (par internet) pour qu'elle me fasse visiter un appartement juste à côté de la maison de ses parents. On a passé la soirée avec son petit frère dans Santa Marta et étant donné qu'ils habitent en direction de parc Tayrona, vers lequel je comptais aller le lendemain pour deux nuits au minimum, je leurs ai proposé que je vienne visiter leur chambre le midi et partir après le déjeuner. J'ai dit que j'étais d'accord pour passer une nuit en rentrant du parc Tayrona trois jours plus tard, pas seulement par ce que je me sentais obligé de leur donner en retour après qu'ils m'eurent naturellement offert repas, conseils etc mais aussi parce que je n'avais pas vraiment eu le temps de prendre des photos de la ville. Pour décrire rapidement la famille, le père a pris sa retraite à 40 ans car il était sergent major, mère au foyer et enfant étudiants. Il y avait une dame allemande, intéressante, gaie et dynamique pour son âge. Elle souhaitait retourner au parc Tayrona après qu'elle eu tout de même fait 4 jours de randonnée pour aller jusqu'à la Ciudad Perdida (le macchu picchu colombien).</p>";

var s_week_4_p3 = "<p>On a réservé deux tentes pour le camping Don Pedro et nous sommes partis, un peu juste, en milieu d'après-midi, car l'entrée pour le parc ferme à 16h, la nuit tombant vite sous les tropiques. S'il y à des plages paradisiaques à Tayrona, c'est d'abord une réserve naturelle, la jungle qu'il faut traverser pendant 45 minutes (par le passage rapide). J'avais laissé la plupart de mes affaires chez la famille de Santa Marta dont mes passeports et heureusement que j'avais la cedula, car depuis deux semaines de nouvelles règles exigeaient que les étrangers montrent leurs passeports. Comme vous pouvez le voir sur les photos (<a href='../../photos/core/?name=Colombia&dir-id=0ByZkBrrzUJN_Tk80ek54eTdnd0U' target='_blank'>ici</a>) on peut avoir des bonnes comme des mauvaises surprises avec la faune. Et la flore est magnifique. Cela change de la République Dominicaine. Ambiance rustique qui ne peut pas faire de mal de temps en temps.</p>";

var s_week_4_p4 = "<p>En fait ma première nuit sous la tente était très saccadée, entre les bruits des animaux exotiques (singes ou autres) pas si lointains. Le vent qui se déplace en tournoiement sur les branches des palmiers comme dans la série LOST et un chat qui s'amuse à vous agripper les pieds et la tête pendant votre sommeil pour vous faire peur ! Le jour se lève à 6h et on était déjà partis avant 7h en direction del Cabo de San Juan, là où les baignades sont autorisées. Il faut une heure de marche pour y parvenir. J'ai donc pu connaître plus amplement Elfi Six qui, comme le montre le contenu de la balise title de la page index de son site <a href='http://cosmicresonance.com' target='_blank'>cosmicresonance</a>, est spécialisée en « Acutonics, Bodywork, Shiatsu, Oriental Medicine, Movement Analysis, Sound/Music ». On avait donc quelques sujets en commun sur lequels échanger. Le chemin pour aller là-bas est incroyable. C'est peut-être dans ce parc que se trouvait Atlantide...</p>";

var s_week_4_p5 = "<p>En ce qui concerne la météo, il fait tout le temps beau depuis le début et la famille de Santa Marta m'a dit qu'il n'a pas plut depuis plus de 6 mois, ce que j'ai un peu de mal à croire. On passe notre journée à marcher, bronzer, dormir, se baigner, écouter de la musique, prendre des photos, disctuer et surtout s'hydrater. On est encore plus affamés la seconde nuit et on décide de se coucher tôt. De toutes les façons je souhaite partir tôt le lendemain pour profiter de la journée à Santa marta. Je prends cette fois-ci des photos de jour. Ca cogne assez, il n'y a pas trop de vent et je pense avoir eu une insolation car le soir et le lendemain je me sens bien fébrile et fiévreux (D'ailleurs j'ai dormis le double que d'habitude ce soir là). Le père m'a fait découvrir <a href='https://fr.airbnb.com' target='_blank'>AirBnb</a> par lequel j'ai trouvé ma nuit suivante à Barranquilla. Le concept est un peu à cheval entre booking et couchsurfing.</p>";

var s_week_4_p6 = "<p>Il y a bien 2h de bus entre Santa marta et Barranquilla et 2h30 entre Barranquilla et Cartagena de India comme le prévoit google maps. Barranquilla est une grille ville (160 km2, plus grande que paris) où il n'y a pas grand chose à voir. Mais je ne regrette pas de m'y être arrêté car c'était plus agréable de faire le voyage en deux temps. Aussi j'ai rencontré plusieurs personnes intéressantes : une fille très sympathique et souriante qui vit avec ses petits frères car ses parents sont séparés. Aussi, surtout un jeune étudiant de 23 ans en lettres modernes, parfaitement bilingue en français, professeur depuis peu à l'alliance française et qui étrangement ne parle pas un mot d'anglais. J'ai dormi chez une dame qui était fille parmi 13 autres frères et sœurs!!!</p>";

var s_week_4_p7 = "<p>Je suis parti le lendemain avant midi pour Cartagena, le trafic était dense et sur la route j'ai vu une scène qui m'était inconnue auparavant : des vautours dévorants un cadavre de chien. Tout le monde m'a dit qu'il faisait plus chaud à Cartagena mais j'ai trouvé que c'était l'inverse. Sûrement l'habitude au climat, pourtant je n'étais plus malade. J'ai décidé de passer mes 4 dernières nuits, sur recommandation d'Elfi, dans la Casona Getsemani pour environ 30 dollars US par nuit. Cartagena pour résumer, c'est bien différent des villes précédentes. Cela doit certainement ressembler à La Havane (que je ne connais pas). Ville coloniale repeinte de toutes les couleurs, tout comme sa population. Endroit idéal pour les photographes mais assez touristique et cher en conséquence. Il y a aussi de nombreux musées à visiter dont le seul gratuit est celui dédié à l'or. Malheureusement, mon Nexus 5 m'a lâché pendant ce « voyage dans le voyage » ici à Cartagena et les photos mobiles qui alimentaient essentiellement ce carnet de voyage vont s'arrêter là car le portable de remplacement que j'ai acheté à mon retour à "+B+" ne peut pas prendre des photos « publiables ». (L'écran qui a lâché: je suspecte l'humidité et les hautes températures.) J'ai fait moins de rencontres ici étant donné que j'ai dormi à l'hôtel et que la ville est plus touristique. Escale à Cali au retour nécessaire car tempête à "+B+" empêchant l'avion d'atterrir.</p>";

var s_week_5and6 = "<p class='t'>Les deux semaines suivantes</p><p>Trois événements essentiels ont marqué ces deux semaines.</p><p>Je suis sorti dans la fameuse Zona T de "+B+" avec deux locales. Les filles sont très jolies dans cette zone, j'ai fait assez rapidement une analogie avec la chanson intitulée « <a href='http://www.youtube.com/watch?v=9N2Wk8OHBR4' target='_blank'>Lady-T</a> » de Crazy P. C'était l'anniversaire de celle avec qui j'avais d'abord fait connaissance qui elle-même a invité une amie colombo-française. Il n'y a que des jeunes dans ce quartier rempli exclusivement des bars, restaurants, discothèques et rarement des hôtels mais pas d'habitations. La soirée s'est finie un peu tard avec deux garçons rencontrés au cours de la soirée dans la rue pour prendre le taxi.</p><p>La deuxième semaine malheureusement, Sarah l'autre bénévole de l'orphelinat a été opérée de l'appendicite et à l'heure où j'écris ce texte elle doit encore rester quelques jours chez elle en convalescence.</p><p>Enfin, le troisième événement notable fût l'adoption de Kevin, un petit garçon de 5 ans (le plus jeune de son groupe en fait) par une famille de Lille. Et pour cela je pense tout simplement reprendre un mail que j'ai écrit pour mes parents. Le voici.</p>";

var s_week_5and6_p2 = "<p class='t'>Mail du jeudi 20 mars 2014</p><p><i><font color='blue'>«C'était une journée assez particulière. J'ai pu assisté à peu près au même événement que vous aviez pu vivre quand vous êtes venus me chercher avec Matthieu...</p><p>En effet depuis quelque temps je passais un peu plus de temps avec un garçon très mignon de 5 ans (encore plus que moi à au même age) à l'orphelinat qui allait être adopté par une famille de Lille ayant déjà adopté un enfant de 2 ans 7 ans auparavant. Aujourd'hui fût leur première vraie rencontre (après plusieurs sessions sur skype). Barbara et Lorena (sa fille) m'ont demandé d'être là aujourd'hui au cas où il y aurait des problèmes de traduction d'autant plus que car Barbara ne pouvait pas être présente.</p><p>C'était très émouvant, à vrai dire même moi j'étais très ému, pas autant que les parents bien sûr et Kevin (qui va changer de prénom car en france ça passe pas) était bien timide mais en même temps je dirais 'instinctivement' heureux de savoir qu'il allait pouvoir avoir une famille et un grand frêre.</p><p>Pour moi, cette demie heure était aussi étrange comme je le disais au début car c'est à quelque chose près le même scénario que pour nous, mis à part le décalage d'âge plus important. Comme si je pouvais assister à ce à quoi pouvait ressembler l'événement de ma propre adoption. Bon, la famille revient mercredi prochain et ils comptent voyager un peu dans le pays avant de repartir.»</font></i></p>";

var s_week_7and8 = "<p class='t'>Dernière semaine de mars et première d'avril</p><p>Les événements qui ressortent de ces deux semaines sont mes rencontres avec les membres de la famille de Patricia Aldobrandini. D'abord avec Claudio Sanchez Ferre, frère de Patricia, elle-même amie de Diane, une de mes tantes. Je suis allé visiter l'entreprise informatique de Claudio près de la zona-t. On a parlé de mes projets de travail ici, ils m'a donné des conseils notamment sur ce que je pouvais espèrer en terme de salaire au regard de mon profil. J'en ai profité pour imprimer des CVS car je n'avais toujours pas eu l'occasion de le faire depuis mon arrivée.</p><p>Je n'ai pas refusé ensuite l'invitation de Claudio pour un dîner au club privé Nogal qui a subit une explosion à la bombe dix ans auparavant. Le traumatisme a dû bien marqué les esprits car le personel de sécurité fouille encore les voitures avec des chiens, des miroirs etc. L'endroit est luxueux: piscine, squash, quelques chambres d'hôtels et un bon restaurant vers les derniers étages offrant une vue panoramique sur une bonne partie de la capitale.</p>";

var s_week_7and8_p2 = "<p>Seulement trois jours après son arrivée à "+B+", Patricia m'a à son tour convié à un repas de famille chez la soeur aînée (Cécilia, ayant notamment travaillé dans un orphelinat ici). Rendez-vous d'abord à la carrera 9 # 75-50, l'appartement de la grand-mère qui souffre d'alzheimer et se déplace en chaise roulante. Un autre frère était là pour aider au déplacement de la grand-mère. Chez Cécilia, qui vit dans le barrio Santa Anna, vers la calle 110 j'ai rencontré encore une autre soeur plus jeune qui vit à Londres avec son mari et deux petites filles très mignonnes qui parlents plus anglais qu'espagnol. J'ai eu un excellent déjeuner et ça fait beaucoup de bien une fois de temps en temps car même si l'ayant beaucoup répété aux gens ici, je ne l'ai pas encore mentionné dans ce récit de voyage: la cuisine est la première chose qui me manque de France. Le niveau de vie est différent dans ce quartier de la ville, c'est plus américain aussi. Par ailleurs je suis content de manger de la nourriture qui ne me rend pas malade car la journée précédente j'ai eu ma seconde petite gastro sûrment dûe à de l'eau pas très propre ou peut-être même de la nourriture. C'est assez récurent comme problème en Colombie.</p><p>Enfin je me suis inscrit pour 4 semaines, dans un premier temps, pour des cours d'espagnol dans un institut privé à 15 minutes en vélo au nord vers la calle 79 qui démarreront à mon retour de Medellin pour la semana santa.</p>";

var s_5_days_in_mdl = "<p class='t'>Cinq jours à Medellin</p><p>Cette fois-ci j'ai pris un avion dans la matinée à l'aller et dans la soirée au retour pour avoir quasiement 5 jours de voyage. Il y a deux aéroports à proximité de Medellin. J'ai appris vers la fin de mon voyage que je suis passé par le plus grand des deux et aussi le plus éloigné, environ 45 minutes en dehors de la ville. Ma première impression concerne la topographie et la superficie. Différement de Bogotà, Medellin est complètement entourée par les montagnes et la superficie est moindre puisque moins de 400 km2. A Bogotà quand il fait nuit ou que le temps est nuageux on s'oriente en fonction des montagnes situées à l'est. J'ai ensuite prêté attention à la température mais comme je suis arrivé le matin je ne trouvais pas qu'il faisait si chaud. En revanche, un peu plus tard dans le centre ville vers 11h j'ai commencé à sentir réellement la différence avec la capitale. En effet il peut faire jusqu'à 28 degrés au beau milieu de la journée et autour des 20 pendant la nuit: ce sont donc des températures idéales.</p><p>On s'était donnée rendez-vous à une station de métro avec une jeune étudiante chez qui j'allais passé ma première nuit. En l'attendant j'ai acheté un pass annuel de métro gratuit et rechargeable. On est allé directement chez sa famille pour déposer mes affaires et déjeuner avant de repartir. Elle vit dans le nord qui contrairement à la capitale est plus pauvre que le sud: encore une fois c'était assez rustique. Elle m'a prêté sa chambre qui est très bruyante. J'ai quasiment dormi dans la rue. Pour une nuit cela me convenait.</p>";

var s_5_days_in_mdl_p2 = "<p>Laura m'a proposé d'aller visiter en fin de journée les locaux de son petit ami, comme moi: développeur web. J'étais très curieux de pouvoir faire une comparaison avec les divers environnements de travail que j'ai connu. Et bien j'ai eu la preuve que Medellin n'a rien a envier à n'importe qu'elle capitale d'un pays complétement développé (c'est à dire sans inégalités de richesse autant prononcées qu'ici) en ce qui concerne le contexte de travail. Bien sûr le bâtiment était très moderne, spatieux, calme, propre. L'endroit me rappelait la bibliothèque françois mitterand de Paris.</p>";

var s_5_days_in_mdl_p3 = "<p>On a visité un peu les environs de la station de métro universidad nacional sans pouvoir visiter le planétarium et le jardin botanique car il était déjà trop tard. On a finalement dîné dans un restaurant italien dans un grand centre commercial et bu un cocktail avant de rentrer.</p><p>Le lendemain matin je me suis rendu par 3 moyens de transports différents jusqu'au lieu de mes 3 suivantes et dernières nuits, au sud ouest cette fois-ci. C'était un appartement où séjournent essentiellement de jeunes étrangers tenu par une très charmante et calme fille originaire de Manizales, Milena. C'était donc mon premier séjour officiel trouvé par l'intermédiaire du site AirBnb. J'ai payé 65€ euros pour 3 nuits comprenant la commision pour le site. L'appartement était à l'image de la ville: grand, spatieux, propre et calme. Cette journée je n'ai pas fait grand chose si ce n'est faire les courses des petits déjeuners à venir, visiter les environs et discuter avec Milena.</p><p>Le lendemain au contraire j'ai rattrapé le temps perdu de la veille. J'ai donc visité le jardin botanique, le planétarium (qui est le plus grand d'amérique latine et le musée d'antioquia qui dispose aussi d'un étage dédié à Fernando Botero à chaque fois en prenant le métro. Je suis rentré pour reposer mes jambes.</p>";

var s_5_days_in_mdl_p4 = "<p>J'ai eu la chance de passer cette troisième soirée en compagnie d'une charmante 'paisa' du même âge que Milena (29 ans), mais les gens paraissent toujours plus jeunes qu'ils sont. Elle m'a donné rendez-vous dans le barrio Poblado qui est l'équivalent de la zona T de Bogotà où l'on a discuté autour d'un très bon dîner et cocktail. On peut tout à fait trouver de la bonne nourriture en Colombie mais c'est pas très évident, le mieux est de dégoter les bons restaurants ce qui tombe bien pour moi qui ne sait presque rien cuisiner.</p>";

var s_5_days_in_mdl_p5 = "<p>Le lendemain je suis allé au Parque de Los Pies Descalzos mais j'étais assez déçu car comme la veille où l'on s'était donné rendez-vous dans un 'parque': un parque à Medellin c'est juste un petit square sans verdure alors qu'à Bogotà un parc est un parc. Cette quatrième journée j'ai perdu une bonne partie de mon après-midi à cause d'un vendeur dans la rue qui après m'avoir rechargé mon forfait m'a assuré qu'il avait aussi 'activé' qui sont deux choses différentes et surtout doivent se faire dans la foulée. J'ai eu en plus l'illusion qu'il avait vraiment activé ma recharge car après une recharge on peut tout de même appeler, envoyer des sms et utiliser internet pendant quelques heures. Mais vers 19h plus rien n'était disponible. C'est un comportement très proche de celui des Indiens qui ont horreur de dire non et veulent toujours vous contenter et préfère mentir en disant qu'ils savent faire ci ou cela alors que ce n'est pas le cas...J'ai du attendre la dernière journée pour aller dans un 'Exito' et faire faire cela par un professionnel.</p><p>Pour ma dernière soirée, nous avons assisté avec Milena et quelque uns de ses amis à un concert d'une chanteuse populaire colombienne. Et pour ma dernière journée: repos avant le voyage de retour.</p>";

var s_weekend_ss_in_ibg = "<p class='t'>Un weekend de Semana Santa à Ibague</p><p>Après 4 jours où j'ai alterné entre cours d'espagnol à l'institut le matin et entretiens d'embauche l'après-midi, j'ai décidé le jeudi que je ne pouvais pas rester à "+B+" pour le weekend de la semaine sainte. J'ai récupéré dans la journée le numéro de portable de Marta, l'amie de Magnolia qui était passée à "+B+" avec un de ses fils Juan José. Je me suis dit que cela pouvait être une bonne idée d'aller leur rendre visite et de connaître le coin d'autant plus que ce n'est qu'à 3 heures de bus pour 14 dollars US alors qu'un aller-retour en avion est aux environs de 150€.</p><p>J'ai mis exactement 3 heures avec un utilitaire qui conduisait dangeureusement et il y a eu quelques accidents sur la route qui nous ont un peu ralenti. Il y a un arrêt au sud ouest de "+B+" non loin de Soacha qui est une 'localité' avoisinante de "+B+" très très pauvre. La sortie de la capitale est donc assez émouvante si c'est la première fois qu'on découvre ces quartiers. Rapidement après, le paysage prend beaucoup de caractère et on a bien deux heures de transport au moins dans des montagnes à couper le souffle. Ibague est 1400m plus proche du niveau de la mer que "+B+" donc plus on avance plus la fraicheur laisse place à la chaleur. Aussi, Ibague est une ville petite en comparaison à Medellin par exemple et si le climat y est à peu près le même, l'air est plus respirable car il y a moins de polution.</p>";

var s_weekend_ss_in_ibg_p2 = "<p>Marta et ses deux fils sur quatre vivent au dernier étage d'un immeuble assez moderne et bien entretenu et peut-être malheureusement (pour son seul défaut) trop exposé au bruit des enfants dans la piscine. L'ainé vit et travaille au Canada, Santiago le second étudie la médecine à Ibague, Diego l'architecture à "+B+" et Juan José va tous les jours dans une école spécialisée pour personne à problème neurologique.</p><p>Marta ne m'attendait pas aussi tôt, je suis arrivé en fait deux heures plus tôt que ce qu'elle avait prévu. Elle nous a préparé à Juan José et moi de très bonnes et originales (avec des ingrédients du pays) lasagnes. L'après-midi je suis resté discuté avec la famille et j'ai secouru Marta qui ne peut plus démarrer son PC avec une distribution Live Linux USB afin qu'elle ait pu sauvegarder ce qui lui semblait vital. J'ai montré d'une manière ludique comment faire de la musique avec l'ordinateur à Juan José. J'avais pris moi aussi mon ordinateur</p><p>Le soir vers 20h j'avais rendez-vous avec Natalia, une fille aux environs de mon âge travaillant dans le domaine de la mode. On a fait rapidement connaissance dans un bar puis nous nous sommes rapprochés du centre pour dîner avec ses amis et sa nièce, Paola qui est à peine plus jeune qu'elle! A un moment donné tout s'est passé comme s'il fallait absolument que je montre une photo de la personne chez qui je vivais pour qu'il se passe quelque chose...Et en effet, Natalia a bien rigolé quand elle a constaté que la personne chez qui j'allais passé mes deux nuits, n'était ni plus ni moins la mère d'un ex petit ami de Paola (la nièce donc de Natalia)!</p>";

var s_weekend_ss_in_ibg_p3 = "<p>Nous avons continué dans le centre ville car Natalia voulait me montrer d'autres endroits mais rapidement nous sommes tombés sur une autre de ses amie qui au sein d'un groupe s'occupaient volontairement et par leurs propres initiatives à donner à boire et manger aux SDF des rues principales de la ville. Nous avons donc enchaîné avec eux et fait leur connaissance tout en servant les plus démunis de la ville.</p><p>C'était une première pour moi qui ait eu vent qu'à travers certains reportages sur TF1 certains soirs d'hiver. Les SDF des grandes villes de Colombie n'ont rien à voir avec ceux de France. Ce n'est pas la température qui leurs pose problème mais plutôt la drogue. C'est bien manifeste que l'origine de leurs problèmes doit se situer dans la drogue car ils ont des lourdes et irréversibles séquelles neurologiques. Leur postures, manière de marcher et expression du visage sont très 'destructurées'. Il n'y avait pas d'hostilité dans l'air, je regardais juste où je mettais les pieds et les yeux des chiens car je pense avoir déjà croisé un chien ayant la rage. Les orages commençaient à éclater au loin on savait qu'il allait pleuvoir on a décider de s'arrêter la pour aujourd'hui et je suis rentré exactement à 23:59 en ayant dit que je rentrerai avant minuit.</p>";

var s_weekend_ss_in_ibg_p4 = "<p>La deuxième journée était vraiment incroyable et pleine de surprises pour moi même si elle a plutôt mal démarré. En effet, Marta nous a dit que nous irions faire une petite rando dans le parque Los Nevados à une heure de bus d'Ibague jusqu'à la finca agroturistica assez tôt le matin pour ne pas être rattrapés par la pluie et l'obscurité. Je me suis levé à 9h et j'étais près une demie heure plus tard mais à 13h on était toujours à l'appartement. C'est le genre de choses qui m'insupportent. On a du arrivé aux alentours de 14h30 au début du point de randonné où nous nous sommes arrêtés pour déjeuner avec une amie de Marta qui s'occupait de Juan José pendant un moment et que Marta considère comme sa fille. A la fin du repas au moment de partir il s'est mis à tomber des cordes.</p><p>Après avoir attendu que cela se calme un peu nous avons décidé de partir tout de même vers le sommet mais nous étions très mal équipés: un parapluie seulement et moi avec un chaud pull à capuche. Sans l'ombre d'un doute pour l'instant le parc Los Nevados est ce qui m'a le plus émerveillé depuis que je voyage dans ce pays. Cet endroit est idéal pour les photos de paysages et je suppose que c'est encore mieux quand les montagnes sont entourées de nuages car cela donne plus de relief aux paysages qui en ont déjà beucoup. Une certaine ambiance mystique aussi. On monte relativement haut et l'air ambiant se fait plus frais. Le temps d'arrivé au premier point de vue spéctaculaire la pluie s'était arrêtée et cela tombait à pic. Il y a un étroit et pentu escalier qui y mène et il faut faire attention même s'il y a des barrières.</p>";

var s_weekend_ss_in_ibg_p5 = "<p>Après une bonne séance de photos on a enchaîné vers la finca mais on rapidement compris qu'on y arriverait pas à temps en continuant à pied donc on a fini le chemin à bord d'une espèce de Jeep. Là haut c'est une véritable surprise qui vous attend. C'est très onirique en fait. Il faut passer un long précipice à bord d'un télephérique qui mène sur un autre versant de la montagne, justement à la finca agro-turistica. C'est le moment paroxystique de la randonnée. Le concept me rappèle un peu celui du parc Tayrona où il faut faire une randonnée pendant quelques heures dans une nature extraodinaire pour parvenir à un site plus ou moins fréquenté par des touristes où l'on peut passer la nuit.</p><p>Quoi qu'il en soit nous n'avions pas prévu de rester et nous sommes rentrés assez rapidement. Mais cette fois-ci pris la pluie puis la nuit ont eur raison de nous. Avant le mirador du milieu de chemin la Jeep de l'aller nous a transporté jusqu'au centre ville d'Ibague.</p><p>Avec Angelica il nous restait un peu de forces le soir pour sortir prendre un pot avec son grand frêre et sa future épouse dans un bar avec une acoustique horrible. La plupart des bar ont un niveau de décibels très élevé et c'est quasi mission impossible pour un étranger de communiquer avec des locaux dans ces circonstances.</p>";

var s_weekend_ss_in_ibg_p6 = "<p>La dernière journée n'était pas vraiment du même ordre que la précédente. Il nous a fallu plus du double du temps mis à l'aller pour rentrer à "+B+" avec Natalia et sa nièce en voiture pour cause de retour de semaine sainte! Quand on se dit qu'il faut seulement 10 minutes en avion... Le mercredi de la semaine suivante c'est l'anniversaire de Natalia, le jeudi d'Angelica et le lendemain encore d'une personne qui à première vue n'a pas sa place dans le récit: Gwenaëlle, ma première amie d'école adoptée à Manizales qui, je l'ai appris par ma famille a décidé de prendre un peu de vacances dans son pays natal.</p>";

var s_last_chapter = "<p class='t' >Réflexions personnelles</p><p>Pourquoi ai-je imaginé l'orphelinat la casa de la madre y del nino comme pouvant avoir des allures de monastère avant d'y aller? Cela ne m'a pas marqué tout de suite mais seulement les dernières fois où je m'y suis rendu avec ma famille d'accueil, qu'il y avait une certaine similitude avec l'idée que je m'en étais faite. En effet si vous regardez mes <a href='https://06e807a852a8f6f4b9a21391ed4aa9650fefd8f8.googledrive.com/host/0ByZkBrrzUJN_Tk80ek54eTdnd0U/2014_03_12_IMG_1267.JPG' target='_blank'>photos</a> du début il se trouve que la cour intérieure carrée avec une petite fontaine et ses plantes peut donner l'allure d'un monastère. Ma mémoire ne peut pas remonter aussi loin, c'est donc une simple coïncidence.</p><p>Au moment du déjeuner, je réalisais que c'était un moment privilégié de pouvoir déjeuner à côté de Barbara 'ma seconde mère' (chronologiquement en tout cas) tout en ayant la vue sur le monserrate.</p><p>En voyageant ici j'ai fini par  réaliser qu'il y avait quelque chose d'incomplet en moi et que le fait de 'boucler la boucle' en revenant me permettait de combler cette incomplétude. L'idée n'est pas difficile à comprendre en soi mais lorsque les gens que je rencontrais me demandaient si c'était la première fois que je voyageais ici: je répondais invariablement que c'était la première fois que je <u>revenais</u> en Colombie et eux me corrigeaient en pensant que je puisse confondre les verbes <u>volver</u> ou <u>regresar</u> avec <u>venir</u> ou <u>viajar</u>. De cette manière, ne puis-je pas dire que je n'ai toujours été qu'en voyage à partir du moment où j'ai quitté ma terre natale (vivre en France et voyager un peu partout dans le monde) et qu'en revenant ici je mets probablement un terme à ce voyage de 28 ans?</p>";

var s_last_chapter_p2 = "<p>Où est le rêve, où est la réalité? Le premier n'existe qu'en dépit de l'autre. En comparaison d'avec la France j'ai vraiment l'impression que c'est un rêve de voyager ici (vivre est très probablement une autre paire de manche) et que je peux faire en sorte que la France qui était ma réalité devienne un vieux cauchemar et par voie de conséquence, la Colombie, initialement un rève, devienne ma nouvelle réalité!</p><p>Quoi qu'il en soit, je me suis surpris à penser plusieurs fois que ce plus long de mes voyages pour l'instant me fait avec nostalgie, redevenir ce petit garçon de 11 ans qui découvrait et vivait une autre vie au Japon.</p><p>C'est assez étrange toutes ces destinées qui se croisent ou recroisent à des dizaines de milliers de kilomètres de son lieu de résidence principale. Je dois rencontrer les jours qui suivent l'écriture de ce chapitre ma première copine, adoptée à Manizales qui a décidé, pour marquer son trentième anniversaire de voyager pendant un mois dans son pays natal. La coïncidence fait que je suis déjà sur place depuis 3 mois. En ce qui concerne les rencontres ce n'est pas ce qui manque dans des grandes capitales du type de Bogota.</p><p>Ce qui me manque de la France: la nourriture. Ce qui me manque plus généralement de l'Europe: les saisons. Surtout cette lumière estivale dense et éternelle des pays du grand nord et d'Europe de l'est qui procure une nostalgie indescriptible avec des mots mais largement perceptible par la musique très 'visuelle' d'Hammock par exemple. (Still Secrets Remaining)<p><audio src='"+s_hammock_song_gdrive+"' preload='none' type='audio/mp3'  controls title='Hammock - Still Secrets Remaining'></audio></p><p>Ici, certes la nature est infiniment plus riche et belle mais la lumière est chaque jour la même: éphémère et agressive.</p>";

var s_last_chapter_p3 = "<p>Mon voyage en Colombie, où j'ai pu y faire quelques 'voyages dans LE voyage' est jusqu'à présent sans conteste 'Le voyage de <a href='../../map' target='_blank'> tous mes voyages</a>'. Pour faire volontairement une liste, "+B+" m'a rappelé par certains aspects autant le Japon que l'Inde ou Los Angeles. Ailleurs comme sur la côté des caraïbes j'avais le sentiment de retrouver le maroc, la crimée ou la république dominicaine. Le comportement des Bogotanais avec le Transmilienio m'a tout de suite rappelé celui des Stambouliotes avec leurs tramways. Dans la zona T de "+B+" je me suis senti revenir à Malte. Il y a une culture du grand mall qu'on retrouve un peu aussi à "+B+" et qui rappelle Dubaï.</p><p>Ce ne sont là que de simples analogies mais la Colombie est bien sûr unique en son genre et j'espère prendre le temps de développer ultérieurement ce point...</p>";

var s_biggest_surprises_p1 = "<p class='t' style='font-size: 20px;'>'Lo que me sorprendió el mas de Colombia'</p><p><u>Points positifs:</u></p><p>- La beauté des femmes. Donc le pourcentage de femmes belles (Medellín en est le meilleur exemple).</p><p>- La pureté de la langue. Meilleur endroit pour s'initier à la langue de Cervantes.</p><p>- La beauté de la nature, des paysages.</p><p>- Le système de prescription d'ordonnance (pour maladie récurrente par exemple): il suffit d'imprimer son ordonnance chaque mois sur internet et d'aller acheter ses médicaments dans sa pharmacie dédiée. On communique par mail ensuite avec son médecin si une consultation n'est pas nécessaire.</p><p>- Le format de la carte d'identité type carte bleue et rentre donc facilement dans le portefeuille (le groupe sanguin se trouve dessus notamment).</p><u>Points négatifs:</u><p>- La surface des trottoirs est plus qu'irrégulière. Cela alterne entre bosses et gros trous. Impossible de marcher en écrivant un texto donc. De toutes les façons il ne vaut mieux pas sortir son portable dans la rue.</p>";

var s_biggest_surprises_p2 = "<p>- L'inutilité des clignotants sur les voitures, personnes ne les utilise.</p><p>- La stupidité des taxis (leur manière de conduire qui est plus qu'accidentogène).</p><p>- Le manque cruel de poubelles à Bogota.</p><p>- Le nombre effrayant de divorces ou séparations.</p><p>- Que les gens s'appellent tous par 'mi amor' mais qu'aucun n'ose dire 'te amo'.</p><p>- Le nombre d'accidents de moto. (Le nombre de jeunes hommes en chaise roulante à Medellín).</p><p>Les femmes défigurées partiellement ou intégralement par des agressions à l'acide qu'on peut croiser dans la rue.</p><p>- Les gens au quai qui ne laissent pas sortir les autres gens du transmilenio avant de rentrer, ce qui coule de sens pourtant!</p><p>- L'instabilité mais surtout la lenteur de la connexion internet. (Si un speed test vous dit 10mo/s il faut en fait diviser presque par 7 pour avoir la valeur réelle qu'on peut observer en téléchargeant avec le protocole torrent). Ce problème physique est dû à la mauvaise infrastructure colombienne et donc trop de paquets se perdent dans les connexions.</p>";

var s_biggest_surprises_p3 = "<p>- Le temps d'attente au caisse de supermarché (dû essentiellement aux comportements des clients et moeurs de fonctionnement général): Les sacs en plastiques sont gratuits. Quand il n'y a pas quelqu'un payé pour remplir les sacs, c'est la caissière qui le fait et le client la regarde faire bien gentiment. Enfin l'opération de multiplication ne semble pas exister aux caisses. À la longue c'est assez frustrant.</p><p>- Le système des adresses paradoxalement empirique en Colombie car même si la plupart des villes fonctionnent en calle (est-ouest) et carrera (nord-sud), une recherche Google Map n\'est pas sûr de vous sortir le bon résultat! Donc avant de vous rendre à un endroit, ayez un screen shot du lieu, des coordonnées pour appeler. Les taxis n'ont pas de GPS. Respectez la précédence entre calle et carrera lorsque vous faîtes une recherche Google Map car sinon vous pouvez avoir des résultats totalement différents.</p><p>- Enfin un point beaucoup plus sujet à controverse: le rapport des colombiens à l'argent. (Peut-être que lorsqu'il vient d'un étranger), si vous PRETEZ de l'argent, faites assez attention à qui vous le prêtez car vous avez peu de chance de revoir votre argent même si la personne vous assure avec bonne foi qu'elle vous le remboursera.</p><p class='t'><u>Autres: </u></p><p>- Que le soleil tape plus à 10h du matin qu'à 2h de l'après-midi.</p><p>- Devoir jeter son papier toilette (usagé bien sûr) dans les poubelles, les wc n'ayant pas suffisamment de pression pour pouvoir accepter le PQ.</p><p>- Le choix assez vaste dans la 'junk food'.</p><p>- Dans les ascenseurs, le rez de chaussé est le 1er étage</p><p>- La plupart des lumières des toilettes se situent à l\'extérieur des toilettes.</p>"

var s_amazon = "<p class='t'><u>Une semaine en Amazonie</u></p><p>J'ai réservé mon voyage une semaine en avance pensant qu'il fallait profiter du fait d'être encore en colombie pour aller visiter un endroit du monde totalement nouveau pour moi. Je n'avais jamais mis les pieds dans l'hémipshère sud ni dans l'amazonie ni au brésil et ni au pérou. Avant le voyage j'ai pensé à acheter un pantalon qui se dissocie au niveau des genoux pour se transformer en short et un bon kway. Ils m'ont été très utiles.</p>";

var s_amazon_p1 = "<p>Le voyage en avion pour Leticia n'est pas long depuis Bogota: seulement 2 heures. Si on commençait à rentrer dans une saison plus fraîche la nuit à Bogota c'était l'inverse en amazonie. Je m'attendais bien à avoir chaleur et humidité en arrivant mais pas de devoir payer un droit d'entrée dans le territoire de 10 dollars US sauf pour les natifs ou résidents de la région. Je monte dans un taxi alors que le centre ville n'est qu'à 10 minutes à pied. Je demande le prix au chauffeur qui me dit 7000 pesos et je lui dis que c'est beaucoup trop cher pour 3 minutes de taxi connaissant relativement les prix après 8 mois de voyages dans le pays. Je lui demande de s'arrêter dans un distributeur de ma banque locale (BBVA). Malheureusement le distributeur ne peut plus distribuer d'argent. Mais heureusement pour moi le taxi n'arrive pas à redémarrer et il me dit que je suis libre de partir car il ne peut pas me rendre la monnaie sur le seul gros billet que j'avais. Il ne me restait plus que 2 minutes de marche pour le centre ville où je cherche un restaurant qui m'a l'air assez sain pour ne pas tomber malade dès le premier jour. Je fais aussi attention de ne pas prendre les glaçons qu'on me propose même si l'on m'assure qu'ils sont fait à base d'eau filtrée.</p>";

var s_amazon_p2 = "<p>Je me balade un peu dans la ville et après avoir constaté qu'il n'y a pas grand chose à voir je demande où je peux prendre le bus pour le kilomètre 11 et le parc tanimboca. Il n'y a pas 36 bus: un pour tabatinga au brésil, un autre pour lagos et un autre pour km 11 ou 20 et après il faut aller au pérou en bateau ou remonter le fleuve amazone en bateau. En revanche il vaut mieux utiliser le bus qui coûte au maximum 2400 pesos pour 25 minutes alors alors qu'un taxi peut facturer 10 fois plus. Au km 11 se trouve à part plusieurs restaurants et une boulangerie, une communauté indigène huitoto, le fleuve Tacana, le parc Tanimboca et le camping <a href='http://omshanty.com' target='_blank'>omshanty</a> tenu par un espagnol, Enrique répondant au surnom de kiké où j'ai passé toutes mes nuits.</p><p>La lumière commence a faiblir à partir de 5:30pm et il fait presque nuit noire une demie heure plus tard donc je n'ai pas fait grand chose cette après-midi si ce n'est prendre des informations sur ce que je pouvais faire le lendemain. Je suis allé à l'entrée du parc Tanimboca pour réserver mon premier dîner trop cher: 15 mille pesos pour une pizza et un jus puis réserver une expédition d'une demie journée pour la matinée suivante. Certains soirs, comme le premier, des villageois regardaient des programmes télévisés à la boulangerie et j'y ai participé en faisant la connaissance de certains. Omshanty et de manière générale le km 11 ont une très bonne ambiance, agréable à vivre car dans la jungle et pas cher du tout. Ce fût une très bonne recommandation d'un ami indirect de mes parents.</p>";

var s_amazon_p3 = "<p>Quand je suis arrivé vers 3h de l'après midi certains indigènes étaient déjà saouls à la bière. Cela me faisait un peu de peine mais c'est en fait assez occasionnel qu'ils soient saouls à cette heure-ci même si les premières bières de la journée sont souvent à 7h du mat et même avant! J'ai aussi goûté au mambé ce premier soir <p><img src='"+s3_url+ipfsHashs[26]+"' style='border: 1px solid #ccc; height:200px; border-radius: 3px; padding: 5px;' /></p> qui soit disant sert à couper la sensation de faim et soif pour travailler plus longtemps et 'aide à penser'. J'ai surtout eu l'impression que cela les abrutissait pas mal quand un des indigènes qui était déjà ivre à ce moment là m'a invité pour rencontrer sa famille. Il a bien rigolé de ma petite blague quand j'ai parlé de la communauté 'hui-toNto' (tonto = stupide) au lieu de huitoto.Il faut prendre une cuillèrée de mambé qu'on garde dans la bouche et l'inhaler au fur et à mesure. C'est à base de la feuille de coca.</p>";

var s_amazon_p4 = "<p>Au fur et à mesure du voyage on réalise que l'amazonie est peut-être l'endroit où les gens sont les plus accueillants de Colombie et les indigènes vivant près de la ville sont des gens comme vous et moi vivant avec eau et électricité mais dans des petites cabanes ou parfois des familles de 5 personnes peuvent dormir dans un seul lit double comme je l'ai vu une fois. Leticia détient par ailleurs les meilleurs statistiques en terme de sécurité. Les dangers viennent plutôt des animaux et des maladies et bien sûr si l'on s'avanture seul dans un endroit trop reculé. Cette semaine là il y eut un nauffrage laissant un mort et un disparu dans un bâteau qui se rendait trop tôt le matin au Pérou alors qu'il faisait encore nuit...</p><p>Avant j'ai pris connaissance de ma chambre qui est en fait constituée de lits individuels avec moustiquaire. J'ai dormi seul le premier soir puis avec 2 polonais tout le reste de la semaine et nous fîmes rejoins par une allemande et un colombien pendant 2 ou 3 nuits. La vie en communauté s'est bien déroulée, on ne s'entend pas ronfler car le bruit des insectes et parfois de la pluie dans la jungle couvre les autres bruits et berçent bien. C'est la première fois de ma vie où j'ai pu être directement et simultanément au contact des 4 autres langues que je pratique ou ai pratiqué à un moment donné de ma vie, l'espagnol bien sûr, l'anglais et parfois même le russe avec les polonais qui savent parler russe et le portugais car la majorité des frontaliers parlent portugais. Je ne parlais pas portugais mais par exemple un soir où un jeune brésilien est venu passé une nuit à omshanty il me parlait principalement en portugais et je lui répondais en espagnol. De cette manière on arrivait à se comprendre. Dans le même registre il est assez fréquent de rencontrer des gens qui ont une triple nationalité ici comme Noémie, cuisinière d'un restaurant ou j'allais petit-déjeuner et dîner au début. Brésilienne par sa mère, péruvienne par son père et colombienne par son mari. J'ai passé une très bonne première nuit et le bruit des insectes de la forêt est vraiment élevé. Il fait même assez frais dans la jungle la nuit, au moins 4 degrés de moins qu'en ville.</p>";

var s_amazon_p5 = "<p>Alors qu'ils m'attendait vers 9h pour faire le tour dans le parc Tanimboca le mardi matin j'ai décidé d'y aller à 8h car j'étais déjà prêt et il faut savoir que le soleil est presque déjà à son zénith à 10 du matin donc autant ne pas attendre. On a commencé par une marche d'un quart d'heure puis escaladé un arbre d'une trentaine de mètres avec l'équipement de sécurité adéquat. J'ai en revanche mis pas mal de temps à me décider à me lancer dans mon premier 'vol' en tyrolienne car c'était assez haut et j'ai constaté dernièrement qu'avec l'âge sûrement, j'étais de plus en plus sujet au vertige même si j'ai déjà fait des sauts en parachutes au début de ma vingtaine. Aussi, la manière dont les câbles sont fixés aux arbres ne m'inspirent pas dutout confiance. C'est très simple, il n'y a rien à faire si ce n'est qu'à se laisser porter par la descente contrairement à un saut en parachute qui requiert une bonne maîtrise de la position de son corps dans le vide. <a href='http://arthur.xn--grgoi-csa.re/#9' target='_blank'>Ici</a> une vidéo prise avec mon appareil photo d'un saut en tyrolienne. S'en suivîrent un passage sur un pont, une descente en rappel, une demie heure de kanoé-kayak et un très bon et copieux repas dans un super cadre.</p><p>Il pleut normalement une fois par jour dans cette région et il a plu pendant que je déjeunais donc ça tombait bien. Le soleil revient très vite ensuite. J'ai parlé avec les 2 cuisinières qui ont des profils assez différents: la plus jeune est une indigène de 24 ans qui a déjà 2 enfants et qui ne vit plus avec le père et ce qui n'est pas typique de la région. La seconde est originaire de Bogota est préfère vivre au contact de la nature d'autant plus qu'elle se considérait trop agée pour rester en ville ce qui me semblait un peu exagéré.</p>";

var s_amazon_p6 = "<p>J'ai profité du temps d'ensoleillement restant dans cette journée pour passer la frontière péruvienne en prenant une barque à moteur pour 3000 pesos le voyage et atteindre l'île de Santa Rosa. Rien à voir et à faire: seulement prendre un pot dans un bar. C'est ambiance 'no mans land' comme souvent aux frontières et le jour où il y a le plus d'ambiance est le dimanche comme à Tabatinga d'ailleurs. On continue de capter les réseaux cellulaires colombiens et datas à Santa Rosa et Tabatinga. Edge pour internet, suffisant pour consulter ses mails et envoyer quelques messages sur whatsapp mais pas plus! De retour au km 11 je dîne au restaurant tenu par Noémie et fait connaissance avec un brésilien au début de sa vingtaine originaire de Sao Pablo. On discute à propos de nos programmes respectifs des jours suivants. Je lui dis que je souhaite aller visiter Puerto narino le lendemain et que lui doit rentrer au Brésil pour le dernier tour des élections présidentielles. On ne se reverra plus.</p><p>Je me lève à 6h pour prendre le premier bâteau en direction de Puerto narino. Il part à 8h de Léticia et le dernier à midi mais dans ces cas là il vaut mieux passer une nuit sur place car il y a deux heures de trajets à l'aller parce que l'embarcation fait une dizaine d'arrêts. Il est vrai qu'il n'y a pas beaucoup de choses à faire au sein même du village mais au moins il est très beau et bien préservé. On circule uniquement à pied ou à vélo. Le village est coloré, plein de plantations et le seul endroit avec un internet permettant uniquement de consulter et envoyer des mails ou autres messages gratuitement est à la mairie. Le soleil tapait très fort ce jour ci, il piquait même. J'avais un t-shirt sur la tête, mes lunettes de soleil de protection 4 et une crème solaire de niveau 50 mais étant aussi proche de l'équateur il ne vaut mieux pas rester plus de 10 voir même 5 minutes idéalement au soleil!</p>";

var s_amazon_p7 = "<p>J'ai beaucoup bu ce deuxième jour, l'organisme devant s'acclimater au changement de température et d'humidité. Un guide local m'a conseillé un bon restaurant qui disposait de beaucoup d'ombre et était même presque obscur. Deux français m'ont invité à leurs tables et c'était très convivial de pouvoir échanger à propos de nos voyages respectifs en Colombie d'une part et de nos profils professionnel d'autre part. Ils avaient passé la trentaine et étaient à la fin d'un voyage d'un mois et demi dans le pays. Elle était journaliste et avait déjà etudié une dizaine de mois en espagne et parlait mieux espangol que lui. Lui était infirmier en milieu psychiatrie en reconversion après avoir travaillé en tant que traducteur dans le domaine du jeu vidéo pendant plusieurs années et donc parlait mieux anglais qu'elle.</p><p>Ils avaient beaucoup d'anecdotes intéressantes à raconter et aussi sur des faits de culture générale. Notamment lorsqu'il m'a expliqué comment le dauphin d'eau douce d'un fleuve de Chine constamment fréquenté par les navires avaient fini par disparaître car le fleuve étant de toutes les façons trop sale il ne restait plus que l'ouïe au dauphin pour se repérer mais le fleuve étant un vacarme, l'environnement n'était ni plus ni moins l'enfer sur terre pour le dauphin qui comme chacun le sait est un animal ne pouvant pas respirer dans l'eau a donc tout le temps une partie du cerveau en éveil et l'autre en sommeil.</p>";

var s_amazon_p8 = "<p>On s'était donné rendez-vous à 13h avec le guide pour qu'il m'emmène plus près des dauphins roses que j'avais pu voir que de loin lors de l'aller jusqu'à puerto narino. Après m'avoir proposé pour 25 dollars US que j'ai réussi à ramener à 15 j'ai du refuser car l'embarcation n'était rien d'autre qu'une barque qui fuyait et n'avait même pas de toit. Autant dire que j'aurais crâmé même si l'<a href='http://fr.wikipedia.org/wiki/Alb%C3%A9do' target='_blank'>albédo</a> de la surface d'un lac est faible contrairement à ce qu'on pourrait croire et j'aurais dû mettre mon kway et crever de chaud. Je n'aurais pas profiter. J'ai donc renoncer à ce mauvais plan.</p><p>Ne pouvant pas rester sous le soleil pour les 45 minutes qui suivîrent, j'ai décidé d'aller voir si la connexion internet de la mairie était suffisament rapide pour recevoir et envoyer des mails. Après quelques échanges avec amis et familles j'ai continué jusqu'au mirador qui n'était pas gratuit mais la vue en vallait la peine. J'ai discuté un quart d'heure avec un local qui m'expliquait un peu les délimitations du village, les différentes activités qu'on pouvait faire dans le coin etc. Arrivé 3:45pm il fallait déjà que je retourne au bâteau du retour qui cette fois-ci était direct. 1h30 pour rentrer avec une bonne drache sur le parcours mais surtout et pour la seconde fois déjà dans mon voyage en amazonie on tombe à sec d'essence à environ 500 mètres de l'arrivée à Léticia et un autre bâteau doit nous ravitailler pour qu'on puisse finir le trajet. Néanmoins j'ai pu assisté au spectacle unique d'un très beau coucher de soleil au-dessus du fleuve amazone. Avant de rentrer au km 11 j'ai recontré une seconde fois Nixon, un guide péruvien à qui j'ai fait une avance de 50 mille pesos pour une excursion que je n'ai jamais faite. J'étais bien fatigué de cette journée. Je crois avoir rapidement dîné et discuté un peu avec les polonais avant d'aller dormir.</p>";

var s_amazon_p9 = "<p>Le jour suivant, jeudi, je n'ai pas fait grand chose d'intéressant. J'ai décidé que j'irai déjeuner à Tabatinga par envie de me retrouver dans une atmosphère différente en attendant de retrouver mon linge propre laissé à Léticia car je n'avais pris qu'un sac à dos pour toute la semaine. De toutes les façons je devais aller en ville car une tempète la veille avait fait tomber des arbres sur des lignes électriques qui nous privèrent d'électricité pendant un jour et demi et mes trois appareils étaient presque à court d'électricité.</p><p>Mon premier contact avec le Brésil est plutôt décevant car Tabatinga est une ville sale, très bruyante, puante comme dans certains quartiers pauvres de villes indiennes et encore plus chaude et humide que Léticia. Pendant mon repas j'ai même du enlever mon t-shirt et mes chaussures pour ne pas être en nage. La bonne surprise en revanche fut au niveau des prises électriques qui sont les mêmes qu'en France et ça tombait bien car j'avais oublié mon convertisseur pour recharger la batterie de mon appareil photo. Encore une fois il a plu pendant mon repas. Le bus entre Tabatinga et Léticia coûte que 2000 pesos et dure une grosse dizaine de minutes.</p><p>J'ai récupéré mon linge et décidé de rentrer car la chaleur des deux dernières journées m'a bien extenué. Ce soir là j'ai fait plus ample connaissance de Christian, originaire de Bogota mais ayant vécu principalement à San Agustin. Il a acheté une cabane auprès des indigènes et se contente du minimum pour vivre. Il est végétarien. Il mesure un mètre 1m85 environ avec des dread locks et toujours vétu d'un jean et d'une chemise Yves Saint Laurent à rayures bleues ciel.</p>";

var s_amazon_p10 = "<p>Il m'a proposé de visiter la propriété de ce qui me disait être la personne ayant 'l'histoire la plus atypique du coin'. Une britannique ayant parcouru pendant 5 mois l'amazone essentiellement en pagode et vécu intégralement comme et au contact des indigènes. Elle a écrit un livre sur cette période de sa vie qui est traduit en espagnol. J'ai pu seulement la saluer car nous sommes allés directement visiter les 3 maisons qui ont toutes 3 une architecture agréable, intéressante et ingénieuse. On a continué ce soir là notre convesation sur sa volonté de reprendre un projet 'ecoturistico' initialement développé par un de ses amis chilien qui ne peut pas donner suite pour plusieurs raisons.</p><p>Le projet se constitue de 7 cabanes à mi chemin entre la route au Km 11 et le fleuve Tacana où l'on peut vivre dans un endroit en s'éduquant sur le fonctionnement de l'écosystème de la jungle amazonienne. Christian m'a déssiné un plan pour que je puisse m'y rendre seul le lendemain matin mais je n'ai pas réussi à trouver bien qu'il m'ai dit par la suite que j'étais sur la bonne voie mais que je ne suis pas allé jusqu'au bout car ces indications sur les temps de marche étaient bien erronées. J'y allais dans le but de prendre des photos et de constater l'état des cabanes qui ne sont plus entretenues et où personne ne vit car il cherche une douzaine de personne devant investir chacune 2000€ environ. Christian cherche à faire entendre à son ami chilien propriétaire de ne pas vendre trop vite les hectares à d'autres qui veulent seulement raser tout ce qu'il y a.</p>";

var s_amazon_p11 = "<p>Je n'ai rien visité de spécial les trois derniers jours. J'ai décidé de vivre un peu plus au contact des gens du coin, sympathiser avec eux, me reposer, en somme vivre plus tranquillement. Le vendredi dans l'après midi je crois après avoir déjeuné une seconde fois à Léticia puis fait la rencontre d'un vénézuelien qui m'a vendu un très beau bracelet ayant du relief un peu à la mnière des coups de poing américain. Il vit avec une italienne originaire des environs de Milan enceinte d'un premier enfant. Je n'ai pas trop saisi le sens de leur voyage en amérique latine et le projet qu'ils avaient derrière...</p>";

var s_amazon_p11_bis = "<p>Le samedi était une journée un peu différente. J'ai accompagné l'après-midi, Noémie faire ses courses à Tabatinga car c'est moins cher et je voulais acheter une petite bouteille de corote (rhum de cachaça) qui ne se trouve que du côté brésilien afin de préparer des caipirinhas pour célébrer mon anniversaire avec les amis du km 11. On a demandé les prix des poissons, acheté fruits et légumes sur le marché et au bord du fleuve. En rentrant, Juan Carlos m'a 'transformé' le corote en caipirinha et on a commencé à boire avec lui, christian et les polonais. Les polonais qui avaient déjà passé la majeure partie de la journée à tester plusieurs drogues en toute hospitalité et convivialité avec les indigènes de cette route qui mène jusqu'à la jungle.</p>";

var s_amazon_p12 = "<p>Le lendemain dimanche 5 octobre était le jour de mon anniversaire et la plupart des villageois me l'ont souhaité. Juan Carlos voulait me baptiser en me jettant un oeuf. J'ai bien vu arriver leur combine et j'ai réussi à ne rien recevoir sur la tronche de la journée. C'était journée de repos encore et j'ai déjeuné au parc Tanimboca en compagnie d'une famille de Guatapé qui s'était installer à Leticia pour que leurs enfants apprennent vite le portugais: décision assez étrange étant donné qu'il y a de nombreux endroits bien plus attrayants que Léticia au Brésil!</p><p>L'après midi je suis rentré à la cabane pour discuter avec les polonais et vers 5:30 pm on est sorti en direction de Santa Rosa puis Tabatinga avec un des guides du parc Tanimboca pour fêter mon anniversaire. Malheureusement avec les élections au Pérou et Brésil il n'y avait aucune animation à Santa Rosa donc on a pris des taxis moto jusqu'à un bar restaurant de plein air situé centre militaire de Tabatinga. Cet endroit donne directement sur le fleuve amazone mais encore une fois la musique et beaucoup trop forte et mauvaise qualité. En se balladant dans Tabatinga ce soir ci je me suis rendu compte que c'était beaucoup plus grand que Léticia. Après avoir goûté à une ou deux bières brésiliennes j'ai décidé de rentrer assez tôt (22:30) car Tabatinga n'est vraiment pas à mon goût. Plus on avance dans la jungle plus l'air se raffraîchi.</p>";

var s_amazon_p13 = "<p>Mon voyage s'arrête là car le lendemain j'ai pris l'avion à mi journée pour Bogota mais je suis tombé malade d'une part en mangeant quelque chose de pas très sain la dernière journée et d'autre part avec le changement de température car les nuits sont très fraîches à partir d'octobre à Bogota: en deçà de 10 degrés et je rappelle qu'il n'y a pas de chauffage. J'ai oublié de mentionné qu'une troisième fois un incident est survenu lors d'un trajet en amazonie lorsqu'un bus allant du km 11 à Léticia a crevé à 2km de l'entrée de la ville et que j'avais déjà payé avant: il faut toujours payer en sortant car sinon le trajet parcouru jusqu'à l'in-accident est offert.</p>";

var container = $('<div />', {css: {margin: 'auto', width: 1300, height: '95%'} }).appendTo($('#sample-viewer'));

	$('<div />', {'class': 'sample-flipbook'})
		.appendTo(container)
		.html('<div><p style="font-size: 50px; margin-top: 10%; margin-bottom: 30px;">Colombie</p><p><a onclick="goToLastPage();">Aller à la dernière page</a></p>'+displayImages({src: s3_url+ipfsHashs[17], w: null, h: '450px' })+'</div>' +
			'<div>'+s_day_1+'</div>' +
			'<div><p style="margin-top: 50px; display: flex;">'+displayImages({ src: s3_url+ipfsHashs[41], w: null, h: '400px' })+displayImages({ src: s3_url+ipfsHashs[18], w: null, h: '400px' })+"</p><p>C'est bien un terrain de golf qu'on aperçoit en arrivant!</p></div>" +
			'<div>'+s_day_2+'</div>' +
			'<div><div style="margin-top: 30px; ">'+displayImages({src: s3_url+ipfsHashs[10], w: '550px', h: null})+'</div></div>'+
			'<div>'+s_day_3+'<p>'+displayImages({src: s3_url+ipfsHashs[1], w: null, h: '370px' })+'</p></div>'+
			'<div>'+s_day_3_bis+'</div>'+
			'<div>'+s_day_4+'<p style="display: flex;">'+displayImages({src: s3_url+ipfsHashs[45], w: null, h: '330px' })+displayImages({src: s3_url+ipfsHashs[44], w: null, h: '330px' })+'</p></div>'+
			'<div>'+s_day_4_bis+displayImages({src: s3_url+ipfsHashs[3], w: '425px', h: null})+s_day_4_bis_p2+'</div>'+
			'<div>'+s_day_5+displayImages({src: s3_url+ipfsHashs[27], w: '400px', h: null})+s_day_5_bis+'</div>'+
			'<div>'+s_day_5_bis_p2+displayImages({src: s3_url+ipfsHashs[55], w: null, h: '450px' })+'</div>'+
			'<div>'+s_day_6+'</div>'+
			'<div><p style="display: flex">'+displayImages({src: s3_url+ipfsHashs[22], w: null, h: '300px' })+displayImages({src: s3_url+ipfsHashs[39], w: null, h: '300px' })+s_day_6_bis+'</p></div>'+
			'<div>'+s_day_7+'</div>'+
			'<div>'+s_day_7_p2+'<p>'+displayImages({src: s3_url+ipfsHashs[40], w: '550px', h: null})+'</p></div>'+
            '<div>'+s_week_2_p1+'</div>'+
            '<div>'+displayImages({src: s3_url+ipfsHashs[7], w: '550px', h: null})+"<p>Rassurant ou non d'avoir des camions de police de la sorte dans son quartier?</p></div>"+
            '<div>'+s_week_2_p2+'</div>'+
            '<div><p>'+displayImages({src: s3_url+ipfsHashs[54], w: null, h: '550px' })+"</p><p>L'université nationale</p></div>"+
            '<div>'+s_week_2_p3+'</div>'+
            '<div><p>'+displayImages({src: s3_url+ipfsHashs[2], w: null, h: '550px' })+"</p><p>Quand il n'y a pas de gardiens...</p></div>"+
            '<div>'+s_week_2_p4+'</div>'+
            '<div>'+s_week_3_p1+'<p>'+displayImages({src: s3_url+ipfsHashs[32], w: '400px', h: null})+'</p></div>'+
            '<div>'+s_week_3_p2+'</div>'+
            '<div><p>'+displayImages({src: s3_url+ipfsHashs[6], w: '550px', h: null})+"</p><p>Un déjeuner à l'orphelinat. Ambience chaleureuse et décontractée. <br/>Idéal pour parfaire son espagnol.</p></div>"+
            '<div>'+s_week_3_p3+'</div>'+
            '<div><p>'+displayImages({src: s3_url+ipfsHashs[24], w: '550px', h: null})+'</p><p>Un café Juan Valdez au centre commercial Carullo le plus proche.</p></div>'+
'<div>'+s_week_4_p1+'</div>'+
              '<div><p>'+displayImages({src: s3_url+ipfsHashs[28], w: '550px', h: null})+'</p></div>'+
             '<div>'+s_week_4_p2+'</div>'+
              '<div><p>'+displayImages({src: s3_url+ipfsHashs[15], w: '550px', h: null})+'</p></div>'+
             '<div>'+s_week_4_p3+'<p>'+displayImages({src: s3_url+ipfsHashs[46], w: '550px', h: null})+'</p></div>'+
              '<div><p>'+displayImages({src: s3_url+ipfsHashs[9], w: '550px', h: null})+'</p><p>Un colibri! (Au plein centre)</p></div>'+
             '<div>'+s_week_4_p4+'<p>'+displayImages({src: s3_url+ipfsHashs[13], w: '500px', h: null})+'</p></div>'+
             '<div>'+s_week_4_p5+'<p style="display: flex">'+displayImages({src: s3_url+ipfsHashs[14], w: null, h: '330px' })+displayImages({src: s3_url+ipfsHashs[50], w: null, h: '330px' })+'</p></div>'+
             '<div><p style="display: flex">'+displayImages({src: s3_url+ipfsHashs[0], w: null, h: '350px' })+displayImages({src: s3_url+ipfsHashs[25], w: null, h: '350px' })+'</p>'+s_week_4_p6+'</div>'+
              '<div><p style="display: flex">'+displayImages({src: s3_url+ipfsHashs[42], w: null, h: '450px' })+displayImages({src: s3_url+ipfsHashs[43], w: null, h: '450px'})+'</p></div>'+
             '<div>'+s_week_4_p7+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[8], w: '550px', h: null})+'</p></div>'+
             '<div><p style="display: flex">'+displayImages({src: s3_url+ipfsHashs[5], w: null, h: '400px'})+displayImages({src: s3_url+ipfsHashs[52], w: null, h: '400px' })+'</p></div>'+'<div><p>'+displayImages({src: s3_url+ipfsHashs[11], w: '550px', h: null})+'</p></div>'+
             '<div>'+s_week_5and6+'</div>'+
             '<div>'+s_week_5and6_p2+'</div>'+
             '<div>'+s_week_7and8+'</div>'+
             '<div>'+s_week_7and8_p2+'</div>'+
             '<div>'+s_5_days_in_mdl+'</div>'+
             '<div><p style="display: flex">'+displayImages({src: s3_url+ipfsHashs[35], w: null, h: '375px' })+displayImages({src: s3_url+ipfsHashs[36], w: null, h: '375px' })+'</p>'+s_5_days_in_mdl_p2+'</div>'+
             '<div>'+s_5_days_in_mdl_p3+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[23], w: '550px', h: null})+'</p>'+s_5_days_in_mdl_p4+'</div>'+
             '<div>'+s_5_days_in_mdl_p5+'</div>'+
             '<div>'+displayImages({src: s3_url+ipfsHashs[29], w: '450px', h: null})+displayImages({src: s3_url+ipfsHashs[20], w: '450px', h: null})+'</div>'+
             '<div>'+s_weekend_ss_in_ibg+'</div>'+
              '<div><p>'+displayImages({src: s3_url+ipfsHashs[31], w: '550px' , h: null})+'</p></div>'+
             '<div>'+s_weekend_ss_in_ibg_p2+'</div>'+
            '<div><p>'+displayImages({src: s3_url+ipfsHashs[37], w: null, h: '600px' })+'</p></div>'+
             '<div>'+s_weekend_ss_in_ibg_p3+'</div>'+
              '<div><p>'+displayImages({src: s3_url+ipfsHashs[30], w: '550px', h: null})+'</p></div>'+
             '<div>'+s_weekend_ss_in_ibg_p4+'</div>'+
              '<div><p>'+displayImages({src: s3_url+ipfsHashs[51], w: '550px', h: null})+'</p></div>'+
             '<div>'+s_weekend_ss_in_ibg_p5+s_weekend_ss_in_ibg_p6+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[21], w: null, h: '600px' })+'</p></div>'+
             '<div>'+s_last_chapter+'</div>'+
             '<div>'+s_last_chapter_p2+'</div>'+
             '<div>'+s_last_chapter_p3+'</div>'+
             '<div>'+s_amazon+displayImages({src: s3_url+ipfsHashs[49], w: '550px' , h: null})+'</div>'+
             '<div>'+s_amazon_p1+'</div>'+
             '<div>'+s_amazon_p2+'</div>'+
             '<div>'+s_amazon_p3+'</div>'+
             '<div>'+s_amazon_p4+'</div>'+
             '<div>'+s_amazon_p5+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[19], w: '550px', h: null})+'</p><p>Les deux jeunes guides du parc Tanimboca.</p></div>'+
             '<div>'+s_amazon_p6+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[16], w: null, h: '480px' })+'</p><p>Fille de Puerto narino se protégeant du soleil avec un parapluie. L\'ombre sur le sol donne une idée de la position du soleil dans le ciel.</p></div>'+
             '<div>'+s_amazon_p7+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[38], w: null, h: '480px' })+'</p><p>Vue depuis le mirador de Puerto narino.</p></div>'+
             '<div>'+s_amazon_p8+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[47], w: '550px', h: null})+'</p><p>Le fameux gros cercle orange cramoisi.</p></div>'+
             '<div>'+s_amazon_p9+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[48], w: '550px', h: null})+'</p><p>L\'entrée de Tabatinga.</p></div>'+
             '<div>'+s_amazon_p10+'</div>'+
             '<div>'+s_amazon_p11+'<p>'+displayImages({src: s3_url+ipfsHashs[4], w: '480px', h: null})+'</p></div>'+
             '<div>'+s_amazon_p11_bis+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[34], w: null, h: '480px' })+'</p><p>Noémie, cuisinière d\'un restaurant du Km 11.</p></div>'+
             '<div>'+s_amazon_p12+s_amazon_p13+'</div>'+
             '<div><p>'+displayImages({src: s3_url+ipfsHashs[12], w: null, h: '480px' })+'</p><p>La moitié des chiens du Km 11 sont boiteux, ecorchés et blessés par les véhicules qui passent. Celui-là ressemble presque à un coyote!</p></div>'+
             '<div>'+s_biggest_surprises_p1+'</div>'+
             '<div>'+s_biggest_surprises_p2+'</div>'+
             '<div>'+s_biggest_surprises_p3+'</div>'+
             '<div><p class="t"><u>Fin</u><a onclick="goToFirstPage();">(Retour à la 1ère page)</a></p><p>'+displayImages({src: s3_url+ipfsHashs[33], w: null, h: '480px' })+'</p></div>');

// Wait until it renders

$('.sample-flipbook').turn({
	width: 1300,
	height: '95%',
	autoCenter: true,
	shadows: $.isTouch,
	acceleration: $.isTouch
});

})(jQuery);
